name: Update Code on Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-code:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Build frontend
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10
        run_install: false
        
    - name: Install frontend dependencies
      run: |
        cd frontend
        pnpm install
        
    - name: Build frontend
      run: |
        cd frontend
        pnpm build
    
    # Deploy backend code to server
    - name: Deploy backend code
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "backend/"
        target: "~/thinkering/pdf_extractor"
        
    # Deploy frontend build to server
    - name: Deploy frontend build
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "frontend/dist/"
        target: "~/thinkering/pdf_extractor/frontend"
        
    # Update dependencies and restart backend
    - name: Update dependencies and restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/thinkering/pdf_extractor/backend
          poetry update
          pm2 reload backend 